name: Sashi
favicon: null
layout_spectrum: 0.65124
typography_spectrum: 0.72348
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b1b1b1'
    - '#100f0b'
    - '#feffbb'
    - '#3d4e08'
    - '#898049'
  brandStrength: 0.6875
  lightness: 0.12436237162910402
  saturation: 0.2108333536889404
  rhythmicContrast: 0.5
purpose: []
